INSERT INTO producer(producer_name, address) VALUES ('ABABABA', 'Wilcza 55');
INSERT INTO producer(producer_name, address) VALUES ('Assdfsd', 'Krolicza 1');
INSERT INTO producer(producer_name, address) VALUES ('sdvsdvdsv', 'Kocia 3');
INSERT INTO producer(producer_name, address) VALUES ('cos', 'Milicka 545');
INSERT INTO producer(producer_name, address) VALUES ('asdasc', 'Owcza 33');
INSERT INTO producer(producer_name, address) VALUES ('qweqwe', 'Ostatnia 155');
INSERT INTO producer(producer_name, address) VALUES ('ABABABA', 'Wilcza 55');
INSERT INTO producer(producer_name, address) VALUES ('Assdfsd', 'Krolicza 1');
INSERT INTO producer(producer_name, address) VALUES ('sdvsdvdsv', 'Kocia 3');
INSERT INTO producer(producer_name, address) VALUES ('cos', 'Milicka 545');
INSERT INTO producer(producer_name, address) VALUES ('asdasc', 'Owcza 33');
INSERT INTO producer(producer_name, address) VALUES ('qweqwe', 'Ostatnia 155');
INSERT INTO producer(producer_name, address) VALUES ('ABABABA', 'Wilcza 55');
INSERT INTO producer(producer_name, address) VALUES ('Assdfsd', 'Krolicza 1');
INSERT INTO producer(producer_name, address) VALUES ('sdvsdvdsv', 'Kocia 3');
INSERT INTO producer(producer_name, address) VALUES ('cos', 'Milicka 545');
INSERT INTO producer(producer_name, address) VALUES ('asdasc', 'Owcza 33');
INSERT INTO producer(producer_name, address) VALUES ('qweqwe', 'Ostatnia 155');
INSERT INTO producer(producer_name, address) VALUES ('ABABABA', 'Wilcza 55');
INSERT INTO producer(producer_name, address) VALUES ('Assdfsd', 'Krolicza 1');
INSERT INTO producer(producer_name, address) VALUES ('sdvsdvdsv', 'Kocia 3');
INSERT INTO producer(producer_name, address) VALUES ('cos', 'Milicka 545');
INSERT INTO producer(producer_name, address) VALUES ('asdasc', 'Owcza 33');
INSERT INTO producer(producer_name, address) VALUES ('qweqwe', 'Ostatnia 155');
INSERT INTO producer(producer_name, address) VALUES ('ABABABA', 'Wilcza 55');
INSERT INTO producer(producer_name, address) VALUES ('Assdfsd', 'Krolicza 1');
INSERT INTO producer(producer_name, address) VALUES ('sdvsdvdsv', 'Kocia 3');
INSERT INTO producer(producer_name, address) VALUES ('cos', 'Milicka 545');
INSERT INTO producer(producer_name, address) VALUES ('asdasc', 'Owcza 33');
INSERT INTO producer(producer_name, address) VALUES ('qweqwe', 'Ostatnia 155');

INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Margheritta', 'Park jesienią Dęby, klany, kasztanowce i jarzębiny mają prawie nagie ramiona. Liście, które na nich pozostały, zmieniły swoją barwę. Tańcząc w rytmie jesiennego wiatru, spadały na niekończące się alejki, tworząc piękny, barwny dywan. Niektóre z nich tańcząc w rytmie jesiennego wiatru z pełną gracją, wyglądały jak tancerki w kolorowych sukienkach. Na skwerku mieszka stary dąb o rozłożystej koronie. Z zadowoleniem rzuca swoje żołędzie dzieciom, które spacerują po pięknej, kolorowej ścieżce. Kasztany i żołędzie rozbiegane po parku, budzą podziw starszych ludzi. Wiewiórki robią zimowe zapasy w swoich domkach. Gołębie z ochotą częstują się okruszkami chleba, które dzieci dla nich wysypały. Jesienią w parku jest bardzo pięknie i kolorowo. Liście na rosnących drzewach zmieniły swój kolor. Są teraz czerwone, żółte i pomarańczowe. Różnokolorowe liście wyglądem przypominają palete farb artysty. Dużo liści już spadło, pokryło trawę i alejki dla spacerujących. W parku jest mały staw gdzie pływają łabędzie. Również wędkarze latem łowią w nim ryby. Jesień to naprawdę piękna pora!', 32, '33.20', 1);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Prosciutto', 'Jesienne chmury są kłębiaste jak wełna . Maja szarawy kolor, lecz na horyzoncie wydaja się jasne jak słońce. Niektóre są wielkie jak słoń inne zaś maleńkie. Goniąc się, po niebie łącza się w coraz większe i większe zakrywając przy tym błękit nieba. Kształtem przypominają czasem owieczki pasące się na hali inne są na kształt statków płynących na morzu. Wiatr popędzając chmury odsłania coraz więcej nieba, słońce coraz bardziej próbuje się wydostać i ogrzewa je swym gorącem. Jesienne chmury są w ciągu jednego dnia puszyste i białe niczym wata cukrowa, żeby za chwilę zamienić się w wielka chmurę gradową z której pada deszcz. Mimo to chmury są naprawdę cudowne , każda jest inna wyjątkowa', 35, '14.20', 2);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Peperoni', 'Czytałem książkę, było cicho i spokojnie. Słychać było jedynie szum wiatru i szelest liści spadających z drzew. Po chwili wiatr zaczął się wzmagać a z nieba zaczęły padać krople deszczu. Nagle zrobiło się ciemno i duszno. Niewiadomo skąd nadciągnęły chmury a z oddali dobiegły delikatne ?pomruki?, Ulica stała się cała błyszcząca jak lustro wody o zachodzie słońca.
Drzewa które dotychczas były nieruchome ,znienacka zaczęły się kołysać. Najpierw delikatnie, potem coraz mocniej, aż wydawało się, że ich pnie nie wytrzymają naporu wzmagającego się wiatru. Liście początkowo podrygujące w lekkich podmuchach wiatru, rozpoczęły zwariowany taniec. A deszcz, który na początku siąpił monotonnie przeszedł nagle w ulewę, która bębniła wściekle po błyskawicznie wyludniających się ulicach. Poboczami zaczęły płynąc strumienie wody porywając spadające liście. Miało się wrażenie, że za chwilę cała ulica zamieni się we rwący, górski potok.
Ludzie, przechadzający się dotychczas leniwym krokiem, biegali nerwowo we wszystkich kierunkach szukając schronienia, nie zważając na powstające niczym jeziora kałuże.
Na ciemniejącym niebie, jak cięcia mieczem, widoczne były białe błyskawice. Początkowy, delikatny pomruk przerodził się w potężne grzmoty ,jakby stado słoni przebiegło po drodze.
Całość przedstawiała piękny i fascynujący widok, który jednocześnie przeraża swoją potęgą.
To całe zjawisko trwało zaledwie pięć minut ale wystarczyło by wzbudzic mój wewnętrzny niepokój.Czytałem książkę, było cicho i spokojnie. Słychać było jedynie szum wiatru i szelest liści spadających z drzew. Po chwili wiatr zaczął się wzmagać a z nieba zaczęły padać krople deszczu. Nagle zrobiło się ciemno i duszno. Niewiadomo skąd nadciągnęły chmury a z oddali dobiegły delikatne ?pomruki?, Ulica stała się cała błyszcząca jak lustro wody o zachodzie słońca.
Drzewa które dotychczas były nieruchome ,znienacka zaczęły się kołysać. Najpierw delikatnie, potem coraz mocniej, aż wydawało się, że ich pnie nie wytrzymają naporu wzmagającego się wiatru. Liście początkowo podrygujące w lekkich podmuchach wiatru, rozpoczęły zwariowany taniec. A deszcz, który na początku siąpił monotonnie przeszedł nagle w ulewę, która bębniła wściekle po błyskawicznie wyludniających się ulicach. Poboczami zaczęły płynąc strumienie wody porywając spadające liście. Miało się wrażenie, że za chwilę cała ulica zamieni się we rwący, górski potok.
Ludzie, przechadzający się dotychczas leniwym krokiem, biegali nerwowo we wszystkich kierunkach szukając schronienia, nie zważając na powstające niczym jeziora kałuże.
Na ciemniejącym niebie, jak cięcia mieczem, widoczne były białe błyskawice. Początkowy, delikatny pomruk przerodził się w potężne grzmoty ,jakby stado słoni przebiegło po drodze.
Całość przedstawiała piękny i fascynujący widok, który jednocześnie przeraża swoją potęgą.
To całe zjawisko trwało zaledwie pięć minut ale wystarczyło by wzbudzic mój wewnętrzny niepokój.Czytałem książkę, było cicho i spokojnie. Słychać było jedynie szum wiatru i szelest liści spadających z drzew. Po chwili wiatr zaczął się wzmagać a z nieba zaczęły padać krople deszczu. Nagle zrobiło się ciemno i duszno. Niewiadomo skąd nadciągnęły chmury a z oddali dobiegły delikatne ?pomruki?, Ulica stała się cała błyszcząca jak lustro wody o zachodzie słońca.
Drzewa które dotychczas były nieruchome ,znienacka zaczęły się kołysać. Najpierw delikatnie, potem coraz mocniej, aż wydawało się, że ich pnie nie wytrzymają naporu wzmagającego się wiatru. Liście początkowo podrygujące w lekkich podmuchach wiatru, rozpoczęły zwariowany taniec. A deszcz, który na początku siąpił monotonnie przeszedł nagle w ulewę, która bębniła wściekle po błyskawicznie wyludniających się ulicach. Poboczami zaczęły płynąc strumienie wody porywając spadające liście. Miało się wrażenie, że za chwilę cała ulica zamieni się we rwący, górski potok.
Ludzie, przechadzający się dotychczas leniwym krokiem, biegali nerwowo we wszystkich kierunkach szukając schronienia, nie zważając na powstające niczym jeziora kałuże.
Na ciemniejącym niebie, jak cięcia mieczem, widoczne były białe błyskawice. Początkowy, delikatny pomruk przerodził się w potężne grzmoty ,jakby stado słoni przebiegło po drodze.
Całość przedstawiała piękny i fascynujący widok, który jednocześnie przeraża swoją potęgą.
To całe zjawisko trwało zaledwie pięć minut ale wystarczyło by wzbudzic mój wewnętrzny niepokój.Czytałem książkę, było cicho i spokojnie. Słychać było jedynie szum wiatru i szelest liści spadających z drzew. Po chwili wiatr zaczął się wzmagać a z nieba zaczęły padać krople deszczu. Nagle zrobiło się ciemno i duszno. Niewiadomo skąd nadciągnęły chmury a z oddali dobiegły delikatne ?pomruki?, Ulica stała się cała błyszcząca jak lustro wody o zachodzie słońca.
Drzewa które dotychczas były nieruchome ,znienacka zaczęły się kołysać. Najpierw delikatnie, potem coraz mocniej, aż wydawało się, że ich pnie nie wytrzymają naporu wzmagającego się wiatru. Liście początkowo podrygujące w lekkich podmuchach wiatru, rozpoczęły zwariowany taniec. A deszcz, który na początku siąpił monotonnie przeszedł nagle w ulewę, która bębniła wściekle po błyskawicznie wyludniających się ulicach. Poboczami zaczęły płynąc strumienie wody porywając spadające liście. Miało się wrażenie, że za chwilę cała ulica zamieni się we rwący, górski potok.
Ludzie, przechadzający się dotychczas leniwym krokiem, biegali nerwowo we wszystkich kierunkach szukając schronienia, nie zważając na powstające niczym jeziora kałuże.
Na ciemniejącym niebie, jak cięcia mieczem, widoczne były białe błyskawice. Początkowy, delikatny pomruk przerodził się w potężne grzmoty ,jakby stado słoni przebiegło po drodze.
Całość przedstawiała piękny i fascynujący widok, który jednocześnie przeraża swoją potęgą.
To całe zjawisko trwało zaledwie pięć minut ale wystarczyło by wzbudzic mój wewnętrzny niepokój.', 12, '10.20', 3);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Rower', 'Mój przyjaciel ma na imię Franek. Jest w moim wieku i chodzi ze mną do klasy. Znamy się od podstawówki. Mieszka niedaleko i często go odwiedzam.
Ma on ciemne, krótkie włosy i niebieskie oczy. Na jego twarzy widać kilka piegów. Jest zawsze schludnie i czysto ubrany. Nosi kolorowe podkoszulki i jeansy.
Franek interesuje się sportem i komputerami, podobnie jak ja. Zbiera on również stare monety i ma ich już bardzo dużo. Jest miły i koleżeński, zawsze we wszystkim mi pomaga. Chodzi wciąż uśmiechnięty i zaraża wszystkich dobrym nastrojem. Lubi go cała klasa. Zna wiele dowcipów, z których śmieją się wszyscy, nawet jeśli słyszeli je już wiele razy. Myślę, że niejedna osoba powinna brać z niego przykład.
Nie zamieniłbym swojego przyjaciela na żadnego innego. Uważam, że przyjaźńjest najważniejsza i zawsze powinniśmy o nią walczyć.', 33, '130.20', 5);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Cos', 'Zachód słońca - w każdym zakątku świata inny, zawsze piękny. Szczególnie nad morzem, gdzie odbijające się w wodzie promienie współtworzą z cudowną paletą barw nieba obraz jak z bajki. Kula jakoby z ognia zanurzająca się w głąb morza, powodująca, że wszystkie żyjące istoty wstrzymują na chwilę oddech, by w ciszy oglądać to wspaniałe zjawisko. Gdy jest już cicho, pusto, człowiek spoglądając na zaczerwienione niebo zachwyca się tym, jak stopniowo i powoli znika zza horyzontu. Cudowna, wielka czerwona, kula na tle żółto-czerwonego nieba nigdy się nie znudzi ludziom, bo za każdym razem gdy na nią patrzą, dostrzegają w niej na nowo piękno. Patrząc na zachód słońca przypominają się same radosne chwile. Każdy patrzy z nadzieją, że po zachodzie słońca zacznie się nowy, piękny dzień po schyłku którego znów będzie można podziwiać nowy zachód słońca, oraz niegasnący jego blask. Nie bez powodu niektórzy ludzie dawniej wierzyli, że Słońce to bóg, gdyż widzimy w nim dużo magii która podnosi nas na duchu. Patrzymy niemal z czcią na to niesamowite zjawisko, gdyż za każdym razem ukazuje ono na nowo piękno kończonego się dnia. Czasami razem z tym zachodem słońca topimy w morzu swoje zmartwienia, problemy i myślimy nad tym, jak można ulepszyć swoje życie, by móc korzystać z niego pełną piersią.', 1, '3000.20', 4);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Margheritta', 'Pizza', 32, '33.20', 20);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Margheritta', 'Park jesienią Dęby, klany, kasztanowce i jarzębiny mają prawie nagie ramiona. Liście, które na nich pozostały, zmieniły swoją barwę. Tańcząc w rytmie jesiennego wiatru, spadały na niekończące się alejki, tworząc piękny, barwny dywan. Niektóre z nich tańcząc w rytmie jesiennego wiatru z pełną gracją, wyglądały jak tancerki w kolorowych sukienkach. Na skwerku mieszka stary dąb o rozłożystej koronie. Z zadowoleniem rzuca swoje żołędzie dzieciom, które spacerują po pięknej, kolorowej ścieżce. Kasztany i żołędzie rozbiegane po parku, budzą podziw starszych ludzi. Wiewiórki robią zimowe zapasy w swoich domkach. Gołębie z ochotą częstują się okruszkami chleba, które dzieci dla nich wysypały. Jesienią w parku jest bardzo pięknie i kolorowo. Liście na rosnących drzewach zmieniły swój kolor. Są teraz czerwone, żółte i pomarańczowe. Różnokolorowe liście wyglądem przypominają palete farb artysty. Dużo liści już spadło, pokryło trawę i alejki dla spacerujących. W parku jest mały staw gdzie pływają łabędzie. Również wędkarze latem łowią w nim ryby. Jesień to naprawdę piękna pora!', 32, '33.20', 18);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Prosciutto', 'Jesienne chmury są kłębiaste jak wełna . Maja szarawy kolor, lecz na horyzoncie wydaja się jasne jak słońce. Niektóre są wielkie jak słoń inne zaś maleńkie. Goniąc się, po niebie łącza się w coraz większe i większe zakrywając przy tym błękit nieba. Kształtem przypominają czasem owieczki pasące się na hali inne są na kształt statków płynących na morzu. Wiatr popędzając chmury odsłania coraz więcej nieba, słońce coraz bardziej próbuje się wydostać i ogrzewa je swym gorącem. Jesienne chmury są w ciągu jednego dnia puszyste i białe niczym wata cukrowa, żeby za chwilę zamienić się w wielka chmurę gradową z której pada deszcz. Mimo to chmury są naprawdę cudowne , każda jest inna wyjątkowa', 35, '14.20', 17);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Peperoni', 'Czytałem książkę, było cicho i spokojnie. Słychać było jedynie szum wiatru i szelest liści spadających z drzew. Po chwili wiatr zaczął się wzmagać a z nieba zaczęły padać krople deszczu. Nagle zrobiło się ciemno i duszno. Niewiadomo skąd nadciągnęły chmury a z oddali dobiegły delikatne ?pomruki?, Ulica stała się cała błyszcząca jak lustro wody o zachodzie słońca.
Drzewa które dotychczas były nieruchome ,znienacka zaczęły się kołysać. Najpierw delikatnie, potem coraz mocniej, aż wydawało się, że ich pnie nie wytrzymają naporu wzmagającego się wiatru. Liście początkowo podrygujące w lekkich podmuchach wiatru, rozpoczęły zwariowany taniec. A deszcz, który na początku siąpił monotonnie przeszedł nagle w ulewę, która bębniła wściekle po błyskawicznie wyludniających się ulicach. Poboczami zaczęły płynąc strumienie wody porywając spadające liście. Miało się wrażenie, że za chwilę cała ulica zamieni się we rwący, górski potok.
Ludzie, przechadzający się dotychczas leniwym krokiem, biegali nerwowo we wszystkich kierunkach szukając schronienia, nie zważając na powstające niczym jeziora kałuże.
Na ciemniejącym niebie, jak cięcia mieczem, widoczne były białe błyskawice. Początkowy, delikatny pomruk przerodził się w potężne grzmoty ,jakby stado słoni przebiegło po drodze.
Całość przedstawiała piękny i fascynujący widok, który jednocześnie przeraża swoją potęgą.
To całe zjawisko trwało zaledwie pięć minut ale wystarczyło by wzbudzic mój wewnętrzny niepokój', 12, '10.20', 16);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Rower', 'Mój przyjaciel ma na imię Franek. Jest w moim wieku i chodzi ze mną do klasy. Znamy się od podstawówki. Mieszka niedaleko i często go odwiedzam.
Ma on ciemne, krótkie włosy i niebieskie oczy. Na jego twarzy widać kilka piegów. Jest zawsze schludnie i czysto ubrany. Nosi kolorowe podkoszulki i jeansy.
Franek interesuje się sportem i komputerami, podobnie jak ja. Zbiera on również stare monety i ma ich już bardzo dużo. Jest miły i koleżeński, zawsze we wszystkim mi pomaga. Chodzi wciąż uśmiechnięty i zaraża wszystkich dobrym nastrojem. Lubi go cała klasa. Zna wiele dowcipów, z których śmieją się wszyscy, nawet jeśli słyszeli je już wiele razy. Myślę, że niejedna osoba powinna brać z niego przykład.
Nie zamieniłbym swojego przyjaciela na żadnego innego. Uważam, że przyjaźńjest najważniejsza i zawsze powinniśmy o nią walczyć.', 33, '130.20', 15);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Cos', 'Zachód słońca - w każdym zakątku świata inny, zawsze piękny. Szczególnie nad morzem, gdzie odbijające się w wodzie promienie współtworzą z cudowną paletą barw nieba obraz jak z bajki. Kula jakoby z ognia zanurzająca się w głąb morza, powodująca, że wszystkie żyjące istoty wstrzymują na chwilę oddech, by w ciszy oglądać to wspaniałe zjawisko. Gdy jest już cicho, pusto, człowiek spoglądając na zaczerwienione niebo zachwyca się tym, jak stopniowo i powoli znika zza horyzontu. Cudowna, wielka czerwona, kula na tle żółto-czerwonego nieba nigdy się nie znudzi ludziom, bo za każdym razem gdy na nią patrzą, dostrzegają w niej na nowo piękno. Patrząc na zachód słońca przypominają się same radosne chwile. Każdy patrzy z nadzieją, że po zachodzie słońca zacznie się nowy, piękny dzień po schyłku którego znów będzie można podziwiać nowy zachód słońca, oraz niegasnący jego blask. Nie bez powodu niektórzy ludzie dawniej wierzyli, że Słońce to bóg, gdyż widzimy w nim dużo magii która podnosi nas na duchu. Patrzymy niemal z czcią na to niesamowite zjawisko, gdyż za każdym razem ukazuje ono na nowo piękno kończonego się dnia. Czasami razem z tym zachodem słońca topimy w morzu swoje zmartwienia, problemy i myślimy nad tym, jak można ulepszyć swoje życie, by móc korzystać z niego pełną piersią.', 1, '3000.20', 13);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Margheritta', 'Pizza', 32, '33.20', 14);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Margheritta', 'Park jesienią Dęby, klany, kasztanowce i jarzębiny mają prawie nagie ramiona. Liście, które na nich pozostały, zmieniły swoją barwę. Tańcząc w rytmie jesiennego wiatru, spadały na niekończące się alejki, tworząc piękny, barwny dywan. Niektóre z nich tańcząc w rytmie jesiennego wiatru z pełną gracją, wyglądały jak tancerki w kolorowych sukienkach. Na skwerku mieszka stary dąb o rozłożystej koronie. Z zadowoleniem rzuca swoje żołędzie dzieciom, które spacerują po pięknej, kolorowej ścieżce. Kasztany i żołędzie rozbiegane po parku, budzą podziw starszych ludzi. Wiewiórki robią zimowe zapasy w swoich domkach. Gołębie z ochotą częstują się okruszkami chleba, które dzieci dla nich wysypały. Jesienią w parku jest bardzo pięknie i kolorowo. Liście na rosnących drzewach zmieniły swój kolor. Są teraz czerwone, żółte i pomarańczowe. Różnokolorowe liście wyglądem przypominają palete farb artysty. Dużo liści już spadło, pokryło trawę i alejki dla spacerujących. W parku jest mały staw gdzie pływają łabędzie. Również wędkarze latem łowią w nim ryby. Jesień to naprawdę piękna pora!', 32, '33.20', 12);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Prosciutto', 'Jesienne chmury są kłębiaste jak wełna . Maja szarawy kolor, lecz na horyzoncie wydaja się jasne jak słońce. Niektóre są wielkie jak słoń inne zaś maleńkie. Goniąc się, po niebie łącza się w coraz większe i większe zakrywając przy tym błękit nieba. Kształtem przypominają czasem owieczki pasące się na hali inne są na kształt statków płynących na morzu. Wiatr popędzając chmury odsłania coraz więcej nieba, słońce coraz bardziej próbuje się wydostać i ogrzewa je swym gorącem. Jesienne chmury są w ciągu jednego dnia puszyste i białe niczym wata cukrowa, żeby za chwilę zamienić się w wielka chmurę gradową z której pada deszcz. Mimo to chmury są naprawdę cudowne , każda jest inna wyjątkowa', 35, '14.20', 11);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Peperoni', 'Czytałem książkę, było cicho i spokojnie. Słychać było jedynie szum wiatru i szelest liści spadających z drzew. Po chwili wiatr zaczął się wzmagać a z nieba zaczęły padać krople deszczu. Nagle zrobiło się ciemno i duszno. Niewiadomo skąd nadciągnęły chmury a z oddali dobiegły delikatne ?pomruki?, Ulica stała się cała błyszcząca jak lustro wody o zachodzie słońca.
Drzewa które dotychczas były nieruchome ,znienacka zaczęły się kołysać. Najpierw delikatnie, potem coraz mocniej, aż wydawało się, że ich pnie nie wytrzymają naporu wzmagającego się wiatru. Liście początkowo podrygujące w lekkich podmuchach wiatru, rozpoczęły zwariowany taniec. A deszcz, który na początku siąpił monotonnie przeszedł nagle w ulewę, która bębniła wściekle po błyskawicznie wyludniających się ulicach. Poboczami zaczęły płynąc strumienie wody porywając spadające liście. Miało się wrażenie, że za chwilę cała ulica zamieni się we rwący, górski potok.
Ludzie, przechadzający się dotychczas leniwym krokiem, biegali nerwowo we wszystkich kierunkach szukając schronienia, nie zważając na powstające niczym jeziora kałuże.
Na ciemniejącym niebie, jak cięcia mieczem, widoczne były białe błyskawice. Początkowy, delikatny pomruk przerodził się w potężne grzmoty ,jakby stado słoni przebiegło po drodze.
Całość przedstawiała piękny i fascynujący widok, który jednocześnie przeraża swoją potęgą.
To całe zjawisko trwało zaledwie pięć minut ale wystarczyło by wzbudzic mój wewnętrzny niepokój', 12, '10.20', 10);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Rower', 'Mój przyjaciel ma na imię Franek. Jest w moim wieku i chodzi ze mną do klasy. Znamy się od podstawówki. Mieszka niedaleko i często go odwiedzam.
Ma on ciemne, krótkie włosy i niebieskie oczy. Na jego twarzy widać kilka piegów. Jest zawsze schludnie i czysto ubrany. Nosi kolorowe podkoszulki i jeansy.
Franek interesuje się sportem i komputerami, podobnie jak ja. Zbiera on również stare monety i ma ich już bardzo dużo. Jest miły i koleżeński, zawsze we wszystkim mi pomaga. Chodzi wciąż uśmiechnięty i zaraża wszystkich dobrym nastrojem. Lubi go cała klasa. Zna wiele dowcipów, z których śmieją się wszyscy, nawet jeśli słyszeli je już wiele razy. Myślę, że niejedna osoba powinna brać z niego przykład.
Nie zamieniłbym swojego przyjaciela na żadnego innego. Uważam, że przyjaźńjest najważniejsza i zawsze powinniśmy o nią walczyć.', 33, '130.20', 9);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('cos', 'Zachód słońca - w każdym zakątku świata inny, zawsze piękny. Szczególnie nad morzem, gdzie odbijające się w wodzie promienie współtworzą z cudowną paletą barw nieba obraz jak z bajki. Kula jakoby z ognia zanurzająca się w głąb morza, powodująca, że wszystkie żyjące istoty wstrzymują na chwilę oddech, by w ciszy oglądać to wspaniałe zjawisko. Gdy jest już cicho, pusto, człowiek spoglądając na zaczerwienione niebo zachwyca się tym, jak stopniowo i powoli znika zza horyzontu. Cudowna, wielka czerwona, kula na tle żółto-czerwonego nieba nigdy się nie znudzi ludziom, bo za każdym razem gdy na nią patrzą, dostrzegają w niej na nowo piękno. Patrząc na zachód słońca przypominają się same radosne chwile. Każdy patrzy z nadzieją, że po zachodzie słońca zacznie się nowy, piękny dzień po schyłku którego znów będzie można podziwiać nowy zachód słońca, oraz niegasnący jego blask. Nie bez powodu niektórzy ludzie dawniej wierzyli, że Słońce to bóg, gdyż widzimy w nim dużo magii która podnosi nas na duchu. Patrzymy niemal z czcią na to niesamowite zjawisko, gdyż za każdym razem ukazuje ono na nowo piękno kończonego się dnia. Czasami razem z tym zachodem słońca topimy w morzu swoje zmartwienia, problemy i myślimy nad tym, jak można ulepszyć swoje życie, by móc korzystać z niego pełną piersią.', 1, '3000.20', 8);
INSERT INTO product(product_name, descript, quantity, cost, producer_id) VALUES ('Margheritta', 'Pizza', 32, '33.20', 7);

INSERT INTO USER(username, first_name, last_name, email, password, enabled) values('filip', 'Filip', 'sdfsdf', 'elo123o320@gmail.com', '{noop}123', true);
INSERT INTO USER(username, first_name, last_name, email, password, enabled) values('admin', 'Admin', 'Admin','eloelo320@gmail.com', '{noop}admin', true);
INSERT INTO USER(username, first_name, last_name, email, password, enabled) values('user', 'Admin', 'Admin','szatan@gmail.com', '{noop}123', true);
INSERT INTO ROLE(username, role) values('filip', 'ROLE_ADMIN');
INSERT INTO ROLE(username, role) values('admin', 'ROLE_ADMIN');
INSERT INTO ROLE(username, role) values('user', 'ROLE_USER');